// Generated by `pnpm content:compile`. Do not edit.
import type { ContentManifest } from "./types.generated";

export const content = {
  "buildId": "56da4f511a1e1181",
  "taxonomy": {
    "kinds": {
      "case-study": {
        "label": "Case Studies",
        "singularLabel": "Case study",
        "description": "Product and engineering work grounded in real outcomes",
        "color": "#B7CF9B",
        "order": 1
      },
      "technical-article": {
        "label": "Technical Articles",
        "singularLabel": "Technical article",
        "description": "Technical explorations, implementation notes, and research",
        "color": "#8B5CF6",
        "order": 2
      }
    },
    "topics": {
      "automation": {
        "label": "Automation",
        "color": "#B7CF9B"
      },
      "graphql": {
        "label": "GraphQL",
        "color": "#E535AB"
      },
      "functional-programming": {
        "label": "Functional Programming",
        "color": "#8B5CF6"
      },
      "react": {
        "label": "React",
        "color": "#087EA4"
      },
      "bundler": {
        "label": "Bundler",
        "color": "#F0A000"
      }
    }
  },
  "about": {
    "hero": {
      "eyebrow": "Hi, I'm Hwanhee.",
      "heading": "Building human-centered products through software",
      "description": "Product-minded frontend engineer based in Seoul, turning complex systems into clear, useful experiences."
    },
    "summary": {
      "heading": "A product engineer who enjoys making complex things feel simple.",
      "body": [
        "I work across product thinking, interface design, and frontend engineering.",
        "I care about tools that help teams move faster without hiding how the system works."
      ]
    },
    "principles": [
      {
        "id": "user-impact-always",
        "title": "User impact, always",
        "description": "Users rarely announce friction before they leave. I study behavior and logs to uncover what they do not say, then make experiences clear from the first use. What matters is not what shipped, but how it improved a user's life."
      },
      {
        "id": "buildership",
        "title": "Buildership",
        "description": "I own outcomes beyond role or team boundaries and move toward the root problem first. The priority is the fastest path to clarity—not whose task it was—while protecting the team and the whole Karrot experience."
      },
      {
        "id": "deep-dive",
        "title": "Deep dive",
        "description": "I begin with context and intent, then trace the system down to the lowest useful level. I compare multiple paths, test assumptions, and propose the solution with the clearest trade-offs."
      },
      {
        "id": "speed-small-simple",
        "title": "Speed, small, simple",
        "description": "I move quickly by reducing the problem. Small useful slices, simple systems, and short feedback loops turn uncertainty into evidence without adding weight the team must carry later."
      }
    ],
    "history": {
      "heading": "I have grown by moving between product and engineering.",
      "body": [
        "My work has ranged from internal automation to customer-facing product experiences.",
        "Each role taught me to treat implementation as part of product discovery, not the final handoff."
      ]
    },
    "leadership": {
      "heading": "Leadership is creating room for better decisions.",
      "body": [
        "I clarify ownership, expose trade-offs, and build shared language around difficult technical choices."
      ]
    },
    "problemSolving": {
      "heading": "I look for the system behind the symptom.",
      "body": [
        "A good fix should solve today's problem while making the next problem easier to understand."
      ]
    },
    "maker": {
      "heading": "I am happiest when an idea becomes something people can touch.",
      "description": "Small experiments, interactive explanations, and useful tools keep my practice grounded.",
      "gallery": []
    }
  },
  "experienceIds": [
    "karrot",
    "naver"
  ],
  "experiencesById": {
    "karrot": {
      "id": "karrot",
      "organization": "Karrot",
      "role": "Product Engineer",
      "period": {
        "start": "2025.10",
        "end": "2026.04"
      },
      "summary": "Building tools and product experiences that help local teams move with clarity.",
      "highlights": [
        "Designed automation systems for recurring operational work.",
        "Connected product context with maintainable frontend architecture."
      ],
      "images": [],
      "articleSlugs": [
        "feature-flag"
      ]
    },
    "naver": {
      "id": "naver",
      "organization": "Naver",
      "role": "Frontend Engineer",
      "period": {
        "start": "2025.04",
        "end": "2025.10"
      },
      "summary": "Worked on user-facing web products and the foundations that supported them.",
      "highlights": [
        "Improved shared frontend workflows across product surfaces."
      ],
      "images": [],
      "articleSlugs": []
    }
  },
  "articleSlugs": [
    "feature-flag",
    "why-setstate-is-asynchronous",
    "type-safe-pipe",
    "type-safe-curry",
    "thinking-in-graph"
  ],
  "articlesBySlug": {
    "feature-flag": {
      "title": "From Feature Flags to a Proactive Experiment Monitoring Pipeline",
      "description": "Building a reliable feature rollout system and self-reporting A/B test system for product team.",
      "slug": "feature-flag",
      "date": "2026-07-24",
      "draft": false,
      "kind": "case-study",
      "topics": [
        "automation"
      ],
      "experienceIds": [
        "karrot"
      ],
      "spotlightIn": {
        "home": 1
      },
      "related": [],
      "thumbnail": "./images/stakeholder-conversations.png",
      "thumbnailUrl": "/_content/articles/feature-flag/images/stakeholder-conversations.png",
      "toc": [
        {
          "id": "overview",
          "level": 2,
          "title": "Overview"
        },
        {
          "id": "background",
          "level": 2,
          "title": "Background"
        },
        {
          "id": "the-process",
          "level": 2,
          "title": "The Process"
        },
        {
          "id": "01-identifying-problems",
          "level": 1,
          "title": "01. Identifying Problems"
        },
        {
          "id": "incidents",
          "level": 2,
          "title": "Incidents"
        },
        {
          "id": "a-slow-shutdown",
          "level": 3,
          "title": "A. Slow shutdown"
        },
        {
          "id": "b-manual-experiments",
          "level": 3,
          "title": "B. Manual experiments"
        },
        {
          "id": "c-missed-checkpoints",
          "level": 3,
          "title": "C. Missed checkpoints"
        },
        {
          "id": "operation-data",
          "level": 2,
          "title": "Operation Data"
        },
        {
          "id": "stakeholder-conversations",
          "level": 2,
          "title": "Stakeholder Conversations"
        },
        {
          "id": "synthesis",
          "level": 2,
          "title": "Synthesis"
        },
        {
          "id": "02-building",
          "level": 1,
          "title": "02. Building"
        },
        {
          "id": "solution-overview",
          "level": 2,
          "title": "Solution Overview"
        }
      ]
    },
    "thinking-in-graph": {
      "title": "Thinking in Graph",
      "description": "Moving beyond a REST-shaped GraphQL API toward node-based schemas, single-query patterns, and field-level resolver chains.",
      "slug": "thinking-in-graph",
      "date": "2024-12-07",
      "draft": false,
      "kind": "technical-article",
      "topics": [
        "graphql"
      ],
      "experienceIds": [],
      "spotlightIn": {
        "home": 2
      },
      "related": [],
      "thumbnail": "./images/schema-after-refactor.png",
      "thumbnailUrl": "/_content/articles/thinking-in-graph/images/schema-after-refactor.png",
      "toc": [
        {
          "id": "1-from-a-restful-mindset-to-graphql",
          "level": 1,
          "title": "1. From a RESTful Mindset to GraphQL"
        },
        {
          "id": "11-where-rest-apis-struggle-at-scale",
          "level": 2,
          "title": "1.1. Where REST APIs Struggle at Scale"
        },
        {
          "id": "12-what-graphql-changed",
          "level": 2,
          "title": "1.2. What GraphQL Changed"
        },
        {
          "id": "13-the-practical-advantages",
          "level": 2,
          "title": "1.3. The Practical Advantages"
        },
        {
          "id": "2-i-had-been-using-graphql-like-rest",
          "level": 1,
          "title": "2. I Had Been Using GraphQL Like REST"
        },
        {
          "id": "21-naming-things-like-a-graph",
          "level": 2,
          "title": "2.1. Naming Things Like a Graph"
        },
        {
          "id": "22-the-single-query-pattern",
          "level": 2,
          "title": "2.2. The Single Query Pattern"
        },
        {
          "id": "3-graphql-data-is-a-graph",
          "level": 1,
          "title": "3. GraphQL Data Is a Graph"
        },
        {
          "id": "resolver-chaining-and-field-based-design",
          "level": 2,
          "title": "Resolver Chaining and Field-Based Design"
        },
        {
          "id": "how-the-resolver-chain-works",
          "level": 2,
          "title": "How the Resolver Chain Works"
        },
        {
          "id": "why-field-level-resolvers-help",
          "level": 2,
          "title": "Why Field-Level Resolvers Help"
        },
        {
          "id": "4-a-mid-project-reflection",
          "level": 1,
          "title": "4. A Mid-Project Reflection"
        },
        {
          "id": "41-what-i-am-still-working-through",
          "level": 2,
          "title": "4.1. What I Am Still Working Through"
        },
        {
          "id": "42-graphql-becomes-more-valuable-as-systems-grow",
          "level": 2,
          "title": "4.2. GraphQL Becomes More Valuable as Systems Grow"
        },
        {
          "id": "43-where-i-want-to-go-next",
          "level": 2,
          "title": "4.3. Where I Want to Go Next"
        },
        {
          "id": "5-closing-thoughts",
          "level": 1,
          "title": "5. Closing Thoughts"
        }
      ]
    },
    "type-safe-curry": {
      "title": "Building a Type-Safe Curry Function",
      "description": "Designing a practical loose curry function in TypeScript and deriving its argument and return types with recursive tuple types.",
      "slug": "type-safe-curry",
      "date": "2025-02-01",
      "draft": false,
      "kind": "technical-article",
      "topics": [
        "functional-programming"
      ],
      "experienceIds": [],
      "spotlightIn": {},
      "related": [
        "type-safe-pipe"
      ],
      "thumbnail": "./images/rambda-curry-source.png",
      "thumbnailUrl": "/_content/articles/type-safe-curry/images/rambda-curry-source.png",
      "toc": [
        {
          "id": "0-functional-programming-and-currying",
          "level": 1,
          "title": "0. Functional Programming and Currying"
        },
        {
          "id": "the-principles-behind-functional-programming",
          "level": 2,
          "title": "The Principles Behind Functional Programming"
        },
        {
          "id": "what-is-currying",
          "level": 2,
          "title": "What Is Currying?"
        },
        {
          "id": "why-currying-fits-functional-programming",
          "level": 2,
          "title": "Why Currying Fits Functional Programming"
        },
        {
          "id": "1-defining-the-curry-function",
          "level": 1,
          "title": "1. Defining the Curry Function"
        },
        {
          "id": "11-strict-curry-or-loose-curry",
          "level": 2,
          "title": "1.1. Strict Curry or Loose Curry?"
        },
        {
          "id": "12-the-runtime-implementation",
          "level": 2,
          "title": "1.2. The Runtime Implementation"
        },
        {
          "id": "13-the-first-building-blocks",
          "level": 2,
          "title": "1.3. The First Building Blocks"
        },
        {
          "id": "2-making-the-input-generic",
          "level": 1,
          "title": "2. Making the Input Generic"
        },
        {
          "id": "21-the-problem-with-any",
          "level": 2,
          "title": "2.1. The Problem with any"
        },
        {
          "id": "22-capturing-the-original-function-type",
          "level": 2,
          "title": "2.2. Capturing the Original Function Type"
        },
        {
          "id": "3-partial-tuples-and-rest-parameters",
          "level": 1,
          "title": "3. Partial Tuples and Rest Parameters"
        },
        {
          "id": "31-a-rest-parameter-must-be-of-an-array-type",
          "level": 2,
          "title": "3.1. “A Rest Parameter Must Be of an Array Type”"
        },
        {
          "id": "32-building-partialtuple",
          "level": 2,
          "title": "3.2. Building PartialTuple"
        },
        {
          "id": "33-how-partialtuple-recurses",
          "level": 2,
          "title": "3.3. How PartialTuple Recurses"
        },
        {
          "id": "4-requiring-at-least-one-argument",
          "level": 1,
          "title": "4. Requiring at Least One Argument"
        },
        {
          "id": "41-why-empty-calls-should-be-invalid",
          "level": 2,
          "title": "4.1. Why Empty Calls Should Be Invalid"
        },
        {
          "id": "42-atleastoneparam",
          "level": 2,
          "title": "4.2. AtLeastOneParam"
        },
        {
          "id": "5-deriving-the-curried-return-type",
          "level": 1,
          "title": "5. Deriving the Curried Return Type"
        },
        {
          "id": "remainingparameters",
          "level": 2,
          "title": "RemainingParameters"
        },
        {
          "id": "curriedfunction",
          "level": 2,
          "title": "CurriedFunction"
        },
        {
          "id": "6-the-finished-api",
          "level": 1,
          "title": "6. The Finished API"
        }
      ]
    },
    "type-safe-pipe": {
      "title": "Building a Type-Safe Pipe Function",
      "description": "Designing a curried pipe utility in TypeScript and choosing pragmatic overloads over unlimited recursive type inference.",
      "slug": "type-safe-pipe",
      "date": "2025-02-19",
      "draft": false,
      "kind": "technical-article",
      "topics": [
        "functional-programming"
      ],
      "experienceIds": [],
      "spotlightIn": {},
      "related": [
        "type-safe-curry"
      ],
      "thumbnail": "./images/fp-ts-pipe-overloads.png",
      "thumbnailUrl": "/_content/articles/type-safe-pipe/images/fp-ts-pipe-overloads.png",
      "toc": [
        {
          "id": "1-introducing-pipe",
          "level": 1,
          "title": "1. Introducing pipe"
        },
        {
          "id": "2-two-shapes-for-pipe",
          "level": 1,
          "title": "2. Two Shapes for pipe"
        },
        {
          "id": "immediate-execution-vs-curried-composition",
          "level": 2,
          "title": "Immediate Execution vs. Curried Composition"
        },
        {
          "id": "3-type-safe-composition-in-typescript",
          "level": 1,
          "title": "3. Type-Safe Composition in TypeScript"
        },
        {
          "id": "the-type-requirements",
          "level": 2,
          "title": "The Type Requirements"
        },
        {
          "id": "the-recursive-type-option",
          "level": 2,
          "title": "The Recursive-Type Option"
        },
        {
          "id": "do-real-pipes-need-unlimited-functions",
          "level": 2,
          "title": "Do Real Pipes Need Unlimited Functions?"
        },
        {
          "id": "a-pragmatic-choice-function-overloads",
          "level": 2,
          "title": "A Pragmatic Choice: Function Overloads"
        },
        {
          "id": "4-closing-thoughts",
          "level": 1,
          "title": "4. Closing Thoughts"
        },
        {
          "id": "further-reading",
          "level": 2,
          "title": "Further Reading"
        }
      ]
    },
    "why-setstate-is-asynchronous": {
      "title": "Why Does setState Work Asynchronously?",
      "description": "A deep dive into how React evolved from batching state updates to concurrent rendering and the Lane model.",
      "slug": "why-setstate-is-asynchronous",
      "date": "2026-01-06",
      "draft": false,
      "kind": "technical-article",
      "topics": [
        "react"
      ],
      "experienceIds": [],
      "spotlightIn": {},
      "related": [],
      "thumbnail": "./images/react-lanes.png",
      "thumbnailUrl": "/_content/articles/why-setstate-is-asynchronous/images/react-lanes.png",
      "toc": [
        {
          "id": "part-1-because-it-is-a-more-efficient-structure",
          "level": 1,
          "title": "Part 1: Because It Is a More Efficient Structure"
        },
        {
          "id": "1-ui-fstate-ui-as-a-pure-function",
          "level": 2,
          "title": "1. UI = f(state): UI as a Pure Function"
        },
        {
          "id": "2-a-computational-view-intermediate-steps-do-not-matter",
          "level": 2,
          "title": "2. A Computational View: Intermediate Steps Do Not Matter"
        },
        {
          "id": "3-user-and-developer-experience-stability-over-raw-speed",
          "level": 2,
          "title": "3. User and Developer Experience: Stability over Raw Speed"
        },
        {
          "id": "part-2-optimization-for-a-smoother-user-experience",
          "level": 1,
          "title": "Part 2: Optimization for a Smoother User Experience"
        },
        {
          "id": "1-blocking-rendering-why-does-everything-stutter",
          "level": 2,
          "title": "1. Blocking Rendering: Why Does Everything Stutter?"
        },
        {
          "id": "2-the-expiration-time-model-when-priority-was-enough",
          "level": 2,
          "title": "2. The Expiration Time Model: When Priority Was Enough"
        },
        {
          "id": "3-suspense-broke-the-old-assumptions",
          "level": 2,
          "title": "3. Suspense Broke the Old Assumptions"
        },
        {
          "id": "4-concurrency-reacts-chosen-solution",
          "level": 2,
          "title": "4. Concurrency: React's Chosen Solution"
        },
        {
          "id": "part-3-the-lane-model-for-finer-grained-rendering",
          "level": 1,
          "title": "Part 3: The Lane Model for Finer-Grained Rendering"
        },
        {
          "id": "1-updates-as-a-set-not-a-line-why-bitmasking",
          "level": 2,
          "title": "1. Updates as a Set, Not a Line: Why Bitmasking?"
        },
        {
          "id": "2-which-events-does-react-process-first",
          "level": 2,
          "title": "2. Which Events Does React Process First?"
        },
        {
          "id": "3-how-lanes-drive-scheduling",
          "level": 2,
          "title": "3. How Lanes Drive Scheduling"
        },
        {
          "id": "summary",
          "level": 2,
          "title": "Summary"
        },
        {
          "id": "references-and-further-reading",
          "level": 2,
          "title": "References and Further Reading"
        }
      ]
    }
  },
  "home": {
    "featuredContent": [
      "feature-flag",
      "thinking-in-graph"
    ]
  }
} as const satisfies ContentManifest;

export type ArticleKindId = keyof typeof content.taxonomy.kinds;
export type TopicId = keyof typeof content.taxonomy.topics;
export type ExperienceId = keyof typeof content.experiencesById;
export type ArticleSlug = keyof typeof content.articlesBySlug;
