// Generated by `pnpm content:compile`. Do not edit.

export type TaxonomyEntry = {
  readonly label: string;
  readonly color: string;
};

export type ArticleKind = TaxonomyEntry & {
  readonly singularLabel: string;
  readonly description: string;
  readonly order: number;
};

export type ArticleTocItem = {
  readonly id: string;
  readonly level: 1 | 2 | 3;
  readonly title: string;
};

export type ArticleSummary = {
  readonly title: string;
  readonly slug: string;
  readonly date: string;
  readonly draft: boolean;
  readonly description?: string;
  readonly thumbnail?: string;
  readonly thumbnailUrl?: string;
  readonly kind: string;
  readonly topics: readonly string[];
  readonly spotlightIn: Readonly<Record<string, number>>;
  readonly related: readonly string[];
  readonly toc: readonly ArticleTocItem[];
};

export type WorkSummary = {
  readonly title: string;
  readonly slug: string;
  readonly date: string;
  readonly draft: boolean;
  readonly description?: string;
  readonly thumbnail?: string;
  readonly thumbnailUrl?: string;
  readonly kind: string;
  readonly topics: readonly string[];
  readonly experienceId: string;
  readonly spotlightIn: Readonly<Record<string, number>>;
  readonly toc: readonly ArticleTocItem[];
};

export type Experience = {
  readonly id: string;
  readonly organization: string;
  readonly role: string;
  readonly period: {
    readonly start: string;
    readonly end: string | null;
  };
  readonly summary: string;
  readonly scale: string;
  readonly learning: string;
  readonly highlights: readonly string[];
  readonly images: readonly string[];
  readonly workSlugs: readonly string[];
};

export type ContentManifest = {
  readonly buildId: string;
  readonly taxonomy: {
    readonly kinds: Readonly<Record<string, ArticleKind>>;
    readonly topics: Readonly<Record<string, TaxonomyEntry>>;
  };
  readonly about: About;
  readonly experienceIds: readonly string[];
  readonly experiencesById: Readonly<Record<string, Experience>>;
  readonly articleSlugs: readonly string[];
  readonly articlesBySlug: Readonly<Record<string, ArticleSummary>>;
  readonly workSlugs: readonly string[];
  readonly worksBySlug: Readonly<Record<string, WorkSummary>>;
  readonly home: {
    readonly featuredArticles: readonly string[];
    readonly featuredWorks: readonly string[];
  };
};

export type Narrative = {
  readonly heading: string;
  readonly body: readonly string[];
};

export type About = {
  readonly hero: {
    readonly eyebrow: string;
    readonly heading: string;
    readonly description: string;
    readonly image?: string;
  };
  readonly summary: Narrative;
  readonly principles: readonly {
    readonly id: string;
    readonly title: string;
    readonly description: string;
  }[];
  readonly history: Narrative;
  readonly leadership: Narrative;
  readonly problemSolving: Narrative;
  readonly maker: {
    readonly heading: string;
    readonly description: string;
    readonly gallery: readonly string[];
  };
};

export type Taxonomy = ContentManifest["taxonomy"];
